WebBotPrototypesWeb/Controllers/DirectLineChatController.cs
using Microsoft.Bot.Connector.DirectLine;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

using Microsoft.Bot.Connector.DirectLine.Models;
using WebBotPrototypes.Logic;
using WebBotPrototypes.Models;

namespace WebBotPrototypes.Controllers
{

    public class DirectLineChatController : Controller
    {
        BotHelper botHelper = new BotHelper();

        public async Task<ActionResult> Index()
        {
            // Create an Instance of the Chat object
            Chat objChat = new Chat();

            // Only call Bot if logged in
            if (User.Identity.IsAuthenticated)
            {
                // Pass the message to the Bot 
                // and get the response
                objChat = await botHelper.TalkToTheBot(User, "Hello");
            }
            else
            {
                objChat.ChatResponse = "Must be logged in";
            }

            // Return response
            return View(objChat);
        }

        [HttpPost]
        public async Task<ActionResult> Index(Chat model)
        {
            // Create an Instance of the Chat object
            Chat objChat = new Chat();

            // Only call Bot if logged in
            if (User.Identity.IsAuthenticated)
            {
                // Pass the message to the Bot and get the response
                objChat = await botHelper.TalkToTheBot(User, model.ChatMessage);
            }
            else
            {
                objChat.ChatResponse = "Must be logged in";
            }

            // Return response
            return View(objChat);
        }

        
    }
}

WebBotPrototypesWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebBotPrototypes.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebBotPrototypesWeb/Controllers/VoiceChatBasicController.cs
using System.Web.Mvc;

namespace WebBotPrototypes.Controllers
{
    public class VoiceChatBasicController : Controller
    {
        // GET: VoiceChat
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebBotPrototypesWeb/Controllers/VoiceChatController.cs
using System;
using System.Configuration;
using System.Diagnostics;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebBotPrototypes.Logic;
using WebBotPrototypes.Models;

namespace WebBotPrototypes.Controllers
{
    public class VoiceChatController : Controller
    {
        BotHelper botHelper = new BotHelper();

        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> SendChat(string text)
        {
            JsonResult result = new JsonResult();

            if (text == null || 
                text.Length == 0)
            {
                return result;
            }

            ViewBag.StatusMessage = $"Chat sent: {text}";

            // Create an Instance of the Chat object
            Chat objChat = new Chat();

            // Only call Bot if logged in
            if (User.Identity.IsAuthenticated)
            {
                // Pass the message to the Bot 
                // and get the response
                objChat = await botHelper.TalkToTheBot(User, text);
            }
            else
            {
                objChat.ChatResponse = "Must be logged in";
            }

            result.Data = objChat;

            return result;
        }

        public async Task<ActionResult> GetTextToSpeech(string text, int no)
        {
            if (text == null)
            {
                text = "Kein text angekommen.";
            }

            Debug.WriteLine(no);

            SpeechResult speechResult = new SpeechResult();
            speechResult.TextPartNo = no;
            speechResult.Text = text;

            #region Bing Speech Authentication

            // Note: The way to get api key:
            // Free: https://www.microsoft.com/cognitive-services/en-us/subscriptions?productId=/products/Bing.Speech.Preview
            // Paid: https://portal.azure.com/#create/Microsoft.CognitiveServices/apitype/Bing.Speech/pricingtier/S0
            string bingApiKey = ConfigurationManager.AppSettings["BingSpeechApiKey"];

            Authentication auth = new Authentication(bingApiKey);
            string accessToken;
            
            try
            {
                accessToken = auth.GetAccessToken();
                speechResult.AccessToken = accessToken;
            }
            catch (Exception ex)
            {
                speechResult.ErrorMessage = "GetTextToSpeech --> Failed authentication --> " + ex.Message + " " + ex.ToString();

                JsonResult result = new JsonResult()
                {
                    Data = speechResult
                };
                return result;
            }

            #endregion

            #region Text-To-Speech

            // Debug.WriteLine("Starting TTSSample request code execution.");

            string requestUri = "https://speech.platform.bing.com/synthesize";

            var cortana = new Synthesize();

            cortana.OnAudioAvailable += (s, args) => {
                var input = args.EventData;

                byte[] buffer = new byte[20*1024*1024];
                using (MemoryStream ms = new MemoryStream())
                {
                    int read;
                    while ((read = input.Read(buffer, 0, buffer.Length)) > 0)
                    {
                        ms.Write(buffer, 0, read);
                    }

                    speechResult.SpeechEventData = ms.ToArray(); ;
                }
            };

            //cortana.OnError += ErrorHandler;
            cortana.OnError += (s, e) =>
            {
                var message = $"Unable to complete the TTS request: {e.ToString()}";
                message += e.EventData.Message;
                speechResult.ErrorMessage = message;
            };

            // Reuse Synthesize object to minimize latency
            await cortana.Speak(CancellationToken.None,
                new Synthesize.InputOptions()
                {
                    RequestUri = new Uri(requestUri),
                    // Text to be spoken.
                    Text = text,
                    VoiceType = Gender.Female,
                    // Refer to the documentation for complete list of supported locales.
                    Locale = ConfigurationManager.AppSettings["DefaultLocale"], // "de-DE",
                    // You can also customize the output voice. Refer to the documentation to view the different
                    // voices that the TTS service can output.
                    VoiceName = ConfigurationManager.AppSettings["VoiceName"], // "Microsoft Server Speech Text to Speech Voice (de-De, Hedda)",
                    // Service can return audio in different output format.
                    OutputFormat = AudioOutputFormat.Riff16Khz16BitMonoPcm,
                    AuthorizationToken = "Bearer " + accessToken,
                });

            JsonResult jsonResult = new JsonResult()
            {
                Data = speechResult
            };

            #endregion

            return jsonResult;
        }

    }
}

WebBotPrototypesWeb/Controllers/WebChatController.cs
using System.Web.Mvc;

namespace WebBotPrototypes.Controllers
{

    public class WebChatController : Controller
    {
        // GET: DirectLineChat
        public ActionResult Index()
        {
            return View();
        }
    }

}

WebBotPrototypesWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebBotPrototypesWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebBotPrototypesWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>@System.Configuration.ConfigurationManager.AppSettings["ApplicationTitle"]</h1>
    <p class="lead">@System.Configuration.ConfigurationManager.AppSettings["ApplicationSubTitle"]</p>
</div>


@{ 
    if (bool.Parse(System.Configuration.ConfigurationManager.AppSettings["ShowContentOnlyWhenAuthorize"]))
    {
        if (!Request.IsAuthenticated)
        {
            return;
        }
    }
}

<div class="row">
    <div class="col-md-4">
        <h2>Standard Web Chat</h2>
        <p>
            Standard Chat Control.
        </p>
        <p>@Html.ActionLink("Web Control", "Index", "WebChat", null, new { @class="btn btn-default" } )</p>
        
        @*<li>@Html.ActionLink("Direct Line", "Index", "DirectLineChat")</li>

        <li>@Html.ActionLink("Voice Chat", "Index", "VoiceChat")</li>
        <li>@Html.ActionLink("Voice Recognition", "Index", "VoiceChatBasic")</li>

        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Start &raquo;</a></p>*@

    </div>

    <div class="col-md-4">
        <h2>Direct Line</h2>
        <p>Absolute customizable and personizable.</p>
        <p>@Html.ActionLink("Direct Line", "Index", "DirectLineChat", null, new { @class = "btn btn-default" })</p>
    </div>

    <div class="col-md-4">
        <h2>Voice Chat</h2>
        <p>Chat with your voice, and get answers spoken.</p>
        <p>@Html.ActionLink("Voice Chat", "Index", "VoiceChat", null, new { @class = "btn btn-default" })</p>
    </div>

    <div class="col-md-4">
        <h2>Voice recognition</h2>
        <p>Detect voices and text.</p>
        <p>@Html.ActionLink("Voice Recognition", "Index", "VoiceChatBasic", null, new { @class = "btn btn-default" })</p>
    </div>
</div>